version: "3.3"
services:
  fastqrbot:
    build: .
    image: fastqrbot
    volumes:
      - ./img:/app/img
      - ./covers:/app/covers
    env_file:
    - .env
    container_name: fastqrbot-container
    restart: always
    network_mode: host
